package com.monsa.alura_challenge.LiterAlura.API.Service;

public enum Codigo_idioma {

    ABKHAZ("ab", "Abjasio"),
    AFAR("aa", "Afar"),
    AFRICANOS("af", "Afrikáans"),
    AKAN("ak", "Akán"),
    ALBANIA("sq", "Albanés"),
    AMARICO("am", "Amárico"),
    ARABE("ar", "Árabe"),
    ARAGONES("an", "Aragonés"),
    ARMENIO("hy", "Armenio"),
    ASSAMESE("as", "Asamés"),
    AVARIC("av", "Avar"),
    AVESTAN("ae", "Avéstico"),
    AYMARA("ay", "Aimara"),
    AZERBAIYAN("az", "Azerí"),
    BAMBARA("bm", "Bambara"),
    BASHKIR("ba", "Bashkir"),
    VASCO("eu", "Vasco"),
    BELARUS("be", "Bielorruso"),
    BENGALI("bn", "Bengalí"),
    BIHARI("bh", "Bihari"),
    BISLAMA("bi", "Bislama"),
    BOSNIA("bs", "Bosnio"),
    BRETON("br", "Bretón"),
    BULGARO("bg", "Búlgaro"),
    BURMESE("my", "Birmano"),
    CATALAN("ca", "Catalán"),
    CHAMORRO("ch", "Chamorro"),
    CHECHENIO("ce", "Checheno"),
    CHICHEWA_CHEWA_NYANJA("ny", "Chichewa"),
    CHINO("zh", "Chino"),
    CHUVASHIA("cv", "Chuvasio"),
    CORNUALLES("kw", "Córnico"),
    COREA("ko", "Coreano"),
    CORSO("co", "Corso"),
    CREE("cr", "Cree"),
    CROACIA("hr", "Croata"),
    CHECO("cs", "Checo"),
    DANES("da", "Danés"),
    DIVEHI_DHIVEHI_MALDIVAS("dv", "Maldivo"),
    HOLANDES("nl", "Neerlandés"),
    DZONGKHA("dz", "Dzongkha"),
    INGLES("en", "Inglés"),
    ESPERANTO("eo", "Esperanto"),
    ESTONIA("et", "Estonio"),
    EWE("ee", "Ewe"),
    FAROESE("fo", "Feroés"),
    FIJI("fj", "Fiyiano"),
    FINLANDES("fi", "Finlandés"),
    FRANCES("fr", "Francés"),
    FULA_FULAH_PULAAR_PULAR("ff", "Fula"),
    GALICIA("gl", "Gallego"),
    GEORGIANO("ka", "Georgiano"),
    ALEMAN("de", "Alemán"),
    GRIEGO_MODERNO("el", "Griego"),
    GUARANI("gn", "Guaraní"),
    GUJARATI("gu", "Guyaratí"),
    HAITIANO_CREOLE_HAITIANO("ht", "Criollo haitiano"),
    HAUSA("ha", "Hausa"),
    HEBREO_MODERNO("he", "Hebreo"),
    HERERO("hz", "Herero"),
    HINDI("hi", "Hindi"),
    HIRI_MOTU("ho", "Hiri Motu"),
    HUNGARO("hu", "Húngaro"),
    INTERLINGUA("ia", "Interlingua"),
    INDONESIO("id", "Indonesio"),
    INTERLINGUE("ie", "Interlingue"),
    IRLANDA("ga", "Irlandés"),
    IGBO("ig", "Igbo"),
    INUPIAQ("ik", "Inupiaq"),
    IDO("io", "Ido"),
    ISLANDES("is", "Islandés"),
    ITALIANO("it", "Italiano"),
    INUKTITUT("iu", "Inuktitut"),
    JAPONES("ja", "Japonés"),
    JAVANES("jv", "Javanés"),
    KALAALLISUT_GROENLANDIA("kl", "Groenlandés"),
    CANARES("kn", "Canarés"),
    KANURI("kr", "Kanuri"),
    CACHEMIRA("ks", "Cachemir"),
    KAZAJSTAN("kk", "Kazajo"),
    KHMER("km", "Jemer"),
    KIKUYU_GIKUYU("ki", "Kikuyu"),
    KINYARWANDA("rw", "Kinyarwanda"),
    KIRGUISES_KIRGUISTAN("ky", "Kirguís"),
    KOMI("kv", "Komi"),
    KONGO("kg", "Kongo"),
    KURDO("ku", "Kurdo"),
    KWANYAMA_KUANYAMA("kj", "Kwanyama"),
    LATIN("la", "Latín"),
    LUXEMBURGES("lb", "Luxemburgués"),
    LUGANDA("lg", "Luganda"),
    LIMBURGUES_LIMBURGAN_LIMBURGER("li", "Limburgués"),
    LINGALA("ln", "Lingala"),
    LAO("lo", "Lao"),
    LITUANO("lt", "Lituano"),
    LUBA_KATANGA("lu", "Luba-Katanga"),
    LETONIA("lv", "Letón"),
    MANX("gv", "Manés"),
    MACEDONIA("mk", "Macedonio"),
    MADAGASCAR("mg", "Malgache"),
    MALAYO("ms", "Malayo"),
    MALAYALAM("ml", "Malabar"),
    MALTES("mt", "Maltés"),
    MAORI("mi", "Maorí"),
    MARATI_MARATHI("mr", "Maratí"),
    ISLAS_MARSHALL("mh", "Marshalés"),
    MONGOLIA("mn", "Mongol"),
    NAURU("na", "Nauruano"),
    NAVAJO_NAVAHO("nv", "Navajo"),
    NORUEGO_BOKMAL("nb", "Noruego Bokmal"),
    NDEBELE_DEL_NORTE("nd", "Ndebele del Norte"),
    NEPALI("ne", "Nepalí"),
    NDONGA("ng", "Ndonga"),
    NORUEGO_NYNORSK("nn", "Noruego Nynorsk"),
    NORUEGO("no", "Noruego"),
    NUOSU("ii", "Nuosu"),
    NDEBELE_DEL_SUR("nr", "Ndebele del Sur"),
    OCCITANO("oc", "Occitano"),
    OJIBWE_OJIBWA("oj", "Ojibwa"),
    ANTIGUO_ESLAVO_ECLESIASTICO("cu", "Eslavo Eclesiástico Antiguo"),
    OROMO("om", "Oromo"),
    ORIYA("or", "Oriya"),
    OSETIA_DEL_SUR_OSETIO("os", "Osético"),
    PANJABI_PUNJABI("pa", "Punyabí"),
    PALI("pi", "Pali"),
    PERSA("fa", "Persa"),
    POLACO("pl", "Polaco"),
    PASHTO_PUSHTO("ps", "Pastún"),
    PORTUGUES("pt", "Portugués"),
    QUECHUA("qu", "Quechua"),
    ROMANCHE("rm", "Romanche"),
    KIRUNDI("rn", "Kirundi"),
    RUMANIA_MOLDAVIA_MOLDAVAN("ro", "Rumano"),
    RUSO("ru", "Ruso"),
    SANSCRITO_SAMSKRTA("sa", "Sánscrito"),
    SARDO("sc", "Sardo"),
    SINDHI("sd", "Sindhi"),
    SAMI_DEL_NORTE("se", "Sami del Norte"),
    SAMOA("sm", "Samoano"),
    SANGO("sg", "Sango"),
    SERBIO("sr", "Serbio"),
    GAELICO_ESCOCES("gd", "Gaélico Escocés"),
    SHONA("sn", "Shona"),
    CINGALES_SINGALES("si", "Cingalés"),
    ESLOVACA("sk", "Eslovaco"),
    ESLOVENO("sl", "Esloveno"),
    SOMALI("so", "Somalí"),
    SOUTHERN_SOTHO("st", "Sesotho del Sur"),
    ESPANOL("es", "Español"),
    SUNDANESE("su", "Sundanés"),
    SWAHILI("sw", "Suajili"),
    SWATI("ss", "Swati"),
    SUECO("sv", "Sueco"),
    TAMIL("ta", "Tamil"),
    TELUGU("te", "Telugu"),
    TAYIKISTAN("tg", "Tayiko"),
    TAILANDIA("th", "Tailandés"),
    TIGRINYA("ti", "Tigriña"),
    TIBETANO("bo", "Tibetano"),
    TURKMENISTAN("tk", "Turcomano"),
    TAGALO("tl", "Tagalo"),
    TSWANA("tn", "Setsuana"),
    TONGA_ISLAS_TONGA("to", "Tongano"),
    TURCO("tr", "Turco"),
    TSONGA("ts", "Tsonga"),
    TARTARA("tt", "Tártaro"),
    TWI("tw", "Twi"),
    TAHITIAN("ty", "Tahitiano"),
    UIGHUR_UYGHUR("ug", "Uigur"),
    UCRANIA("uk", "Ucraniano"),
    URDU("ur", "Urdu"),
    UZBEKO("uz", "Uzbeko"),
    VENDA("ve", "Venda"),
    VIETNAMITA("vi", "Vietnamita"),
    VOLAPUK("vo", "Volapük"),
    VALONIA("wa", "Valón"),
    GALES("cy", "Galés"),
    WOLOF("wo", "Wolof"),
    OESTE_DE_FRISIA("fy", "Frisón Occidental"),
    XHOSA("xh", "Xhosa"),
    YIDDISH("yi", "Yidis"),
    YORUBA("yo", "Yoruba"),
    ZHUANG_CHUANG("za", "Zhuang"),
    ZULU("zu", "Zulú");

    private String codigo;
    private String nombreUppercamel;

    Codigo_idioma(String codigo, String nombreUppercamel) {
        this.codigo = codigo;
        this.nombreUppercamel = nombreUppercamel;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getNombreUppercamel() {
        return nombreUppercamel;
    }

    public static String fromCodigo(String codigo) {
        for (Codigo_idioma idioma : values()) {
            if (idioma.getCodigo().equalsIgnoreCase(codigo)) {
                return idioma.getNombreUppercamel();
            }
        }
        throw new IllegalArgumentException("Ningún código encontrado: " + codigo);
        
    }

}

